import { createServer } from 'vite';import {readFileSync} from 'node:fs';import{fileURLToPath}from'node:url';import{resolve,dirname}from'node:path';import ts from'typescript';
const root=fileURLToPath(new URL('../../',import.meta.url));
const entry=`import React from'react';import{createRoot}from'react-dom/client';import'/src/index.css';import DriverMissionView from'/src/components/DriverMissionView.tsx';
window.missions=[];window.listeners=[];window.parcels=[];window.scanCount=0;
window.scan=async input=>{window.scanCount++;const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Indian/Reunion',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const p={id:input.code,externalId:input.code,orderNumber:input.code,status:'En livraison',missionId:'actual-server-tour',stopId:'first-stop',currentDriverId:'demo',address:'1 rue Fictive',postalCode:'97400',city:'Saint-Denis',contactName:'Destinataire fictif',movements:[]};if(!window.parcels.some(v=>v.id===p.id))window.parcels.push(p);window.missions=[{id:'actual-server-tour',driverId:'demo',driverName:'Chauffeur Fictif',date:day,status:'En cours',type:'Livraison',zone:'Nord',stops:[{id:'first-stop',type:'DELIVERY',status:'En attente',sequence:1,address:p.address,city:p.city,contactName:p.contactName,packageIds:window.parcels.map(p=>p.id),packageCount:window.parcels.length}],totalPackages:window.parcels.length}];window.listeners.forEach(cb=>cb(window.missions));await new Promise(r=>setTimeout(r,150));return{accepted:true,outcome:'confirmed',packageId:input.code,packageCode:input.code,message:'Scan confirmé — tournée du '+day,scannedAt:new Date().toISOString(),missionId:'actual-server-tour',missionDate:day,stopId:'first-stop',driverId:'demo',driverName:'Chauffeur Fictif'};};
createRoot(document.getElementById('root')).render(<DriverMissionView currentUser={{id:'demo',firstName:'Chauffeur',lastName:'Fictif',role:'Chauffeur'}} clients={[]}/>);`;
const custom={subscribeToMissions:'cb=>{window.listeners.push(cb);queueMicrotask(()=>cb(window.missions));return()=>{window.listeners=window.listeners.filter(x=>x!==cb)}}',subscribeToPackages:'cb=>{queueMicrotask(()=>cb([]));return()=>{}}',getPackagesByIds:'async ids=>window.parcels.filter(p=>ids.includes(p.id))',pendingDeliveries:'async()=>[]',outboxChangeEvent:JSON.stringify('fixture-outbox'),getGoogleMapsApiKey:'()=>null',getCurrentPosition:'async()=>({lat:-20.9,lng:55.5})'};
function fakeService(file){const s=readFileSync(file,'utf8'),ast=ts.createSourceFile(file,s,ts.ScriptTarget.Latest,true),out=[];for(const node of ast.statements){if(!node.modifiers?.some(m=>m.kind===ts.SyntaxKind.ExportKeyword))continue;if(ts.isEnumDeclaration(node)){out.push(ts.transpile(node.getText(ast),{module:ts.ModuleKind.ESNext}));continue;}const names=ts.isFunctionDeclaration(node)&&node.name?[node.name.text]:ts.isVariableStatement(node)?node.declarationList.declarations.filter(d=>ts.isIdentifier(d.name)).map(d=>d.name.text):[];for(const name of names)out.push('export const '+name+' = '+(custom[name]||'async()=>[]')+';');}return out.join('\n')+'\nexport default {};'}
const plugin={name:'driver-first-scan',enforce:'pre',resolveId(id,importer){if(id==='/__driver.tsx')return id;if(id.includes('services/scanService'))return '\0scan';if(/firebaseConfig/.test(id))return '\0config';if(importer&&id.includes('services/')&&!id.includes('confirmationService'))return '\0service:'+resolve(dirname(importer),id.replace(/\.ts$/,''))+'.ts';},load(id){if(id==='/__driver.tsx')return entry;if(id==='\0scan')return 'export const scanPackage=input=>window.scan(input);export const scanReceiptLabel=r=>r.packageCode+" — "+r.message;export const rememberScanMission=()=>{};';if(id==='\0config')return 'export const db={},auth={},storage={};export default {};';if(id.startsWith('\0service:'))return fakeService(id.slice(9));},configureServer(s){s.middlewares.use(async(req,res,next)=>{if(req.url.split('?')[0]!=='/')return next();res.setHeader('Content-Type','text/html');res.end(await s.transformIndexHtml(req.url,'<!doctype html><html lang="fr"><head><meta name="viewport" content="width=device-width,initial-scale=1"/></head><body><div id="root"></div><script type="module" src="/__driver.tsx"></script></body></html>'))})}};
const server=await createServer({root,cacheDir:'/tmp/fleet-driver-scan-vite',server:{host:'127.0.0.1',port:5246,strictPort:true},plugins:[plugin]});await server.listen();console.log('Driver first scan fixture http://127.0.0.1:5246');
