import { createServer } from 'vite';
import { fileURLToPath } from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
const entry=`import React,{useState} from 'react';import{createRoot}from'react-dom/client';import '/src/index.css';
import ClaimScanModal from '/src/components/ClaimScanModal.tsx';import{ManualScanFallback}from'/src/components/Scanner.tsx';import PackageTimeline from '/src/components/PackageTimeline.tsx';
window.calls=[];window.hold=false;window.rejectNext=false;window.seen=new Set();
window.scan=async input=>{window.calls.push(input);if(window.hold)await new Promise(r=>window.release=r);if(window.rejectNext){window.rejectNext=false;throw Error('network');}if(input.code==='0012345678300123450101')return{accepted:false,outcome:'ambiguous',matchedOrderReference:'12345678',message:'Commande 12345678 retrouvée. Scannez le code individuel DELIVREX ou saisissez le numéro BR… imprimé sur ce carton. Aucun colis ajouté avec ce code de commande.',packageCode:input.code,packageId:null};const duplicate=window.seen.has(input.code);window.seen.add(input.code);return{accepted:input.code!=='UNKNOWN',outcome:input.code==='UNKNOWN'?'not_found':duplicate?'already_scanned':'reassigned',message:input.code==='UNKNOWN'?'Colis introuvable':duplicate?'Déjà scanné — tournée du 17/09/2026':'Repris — tournée du 17/09/2026',requestId:crypto.randomUUID(),packageId:input.code,packageCode:input.code,driverId:'demo',driverName:'Chauffeur fictif',scannedAt:'2026-09-17T05:12:30Z',missionId:'tour-demo-17-septembre',missionDate:'2026-09-17',stopId:'stop-demo'};};
function Fixture(){const[open,setOpen]=useState(true);return <><p>Données fictives — aucun accès Firebase</p>{open?<ClaimScanModal currentUser={{id:'demo',firstName:'Chauffeur',lastName:'Fictif',role:'Chauffeur'}} onClose={()=>setOpen(false)} onDone={(count,id)=>{window.done={count,id};setOpen(false)}}/>:<button onClick={()=>setOpen(true)}>Rouvrir</button>}</>}
function Fallback(){const[feedback,setFeedback]=useState(null);return<ManualScanFallback title="Scanner un colis" onScan={code=>{window.fallbackCode=code;setFeedback({type:'ok',text:'Scan confirmé — tournée du 17/09/2026'})}} onClose={()=>{}} flashMessage={feedback}/>}
createRoot(document.getElementById('root')).render(location.search.includes('fallback')?<Fallback/>:location.search.includes('timeline')?<PackageTimeline showActors showInternalDetails movements={[{action:'SCANNED',timestamp:'2026-09-17T05:12:30Z',missionId:'tour-demo-17',missionDate:'2026-09-17',fromMissionId:'tour-demo-16',fromMissionDate:'2026-09-16',driverName:'Chauffeur fictif',outcome:'reassigned'}]}/>:<Fixture/>);`;
const plugin={name:'scan-fixture',enforce:'pre',resolveId(id){if(id.includes('services/scanService'))return '\0scan';if(id.includes('services/missionService'))return '\0mission';if(id.includes('services/activityLogService'))return '\0activity';if(id.includes('services/logService'))return '\0log';},load(id){
if(id==='\0scan')return `export const scanPackage=input=>window.scan(input);export const scanReceiptLabel=r=>r.packageCode+' — '+r.message+' à 09:12:30';`;
if(id==='\0mission')return `export const createAndClaimPackage=()=>{throw Error('Not part of this fixture')};`;
if(id==='\0activity')return 'export const logActivity=async()=>{};';if(id==='\0log')return 'export const reportError=()=>{};';},configureServer(server){server.middlewares.use(async(req,res,next)=>{if(req.url.startsWith('/__scan.tsx')){res.setHeader('Content-Type','application/javascript');res.end((await server.transformRequest('/__scan-entry.tsx')).code);return;}if(req.url.split('?')[0]!=='/')return next();res.setHeader('Content-Type','text/html');res.end(await server.transformIndexHtml(req.url,'<!doctype html><html lang="fr"><head><meta name="viewport" content="width=device-width,initial-scale=1"/></head><body><div id="root"></div><script type="module" src="/__scan-entry.tsx"></script></body></html>'));})}};
const server=await createServer({root,cacheDir:'/tmp/fleet-scan-vite',server:{host:'127.0.0.1',port:5245,strictPort:true},plugins:[plugin,{name:'entry',resolveId:id=>id==='/__scan-entry.tsx'?id:null,load:id=>id==='/__scan-entry.tsx'?entry:null}]});await server.listen();console.log('Scan fixture http://127.0.0.1:5245');
